### ISSUE TITLE
License

### ISSUE THREAD

**Issue by linusg** [zig-community/user-map#47]
Hey all, this looks really cool! It seems like there's no license in the repo though, would you mind adding one? Would certainly make forking the code as a basis for other project's maps more straightforward. Thanks!

**Comment by kristoff-it** [comment]
SerenityOS usermap incoming? :^)

**Comment by linusg** [comment]
I think so! :^)

**Comment by MasterQ32** [comment]
Yeah, good idea. We just need to figure out how to apply the licence *not* to the `people` folder, as those are definitly not "open source" in the terms that other people can do what they want with it

**Comment by Luukdegram** [comment]
Thank you for this linusg, we've included a license in #51
